### ISSUE TITLE
Application not compiling on XCode 10 and on iOS 12 device 

### ISSUE THREAD

**Issue by rajesht1989** [google/promises#49] opened 2018-06-05 08:05 UTC
There seems to be an issue while converting Promise to FBLPromise. Completly blocked. 

2.	While generating Objective-C header
3.	While printing 'Connection' at /Volumes/Official/WorkingCopy/native/Classes/Swift/Connection/Connection.swift:11:1
4.	While printing type 'Promise<User>.ObjCPromise<User>'
5.	While printing type 'Value'
error: Segmentation fault: 11

**Comment by shoumikhin** [comment] 2018-06-05 23:11
Hi Rajesh, thank you for the heads up!

Could you provide some code snippets or a small test project that fails for you on Xcode 10, please?
Can you also open Promises.xcworkspace on your side and confirm all tests pass?

Thanks.

**Comment by rajesht1989** [comment] 2018-06-06 12:32
Objc code 

 ```
    [Test callMeObjc].then(^id(NSNumber *number) {
         NSLog(@"%@",number);
         return nil;
     });
```
 
Swift class

```
 class Test : NSObject {
     
     static func callMeObjc() - Promise<Bool.ObjCPromise<NSNumber {
         return callMe().then({ (value) in
             return NSNumber(value: value)
         }).asObjCPromise()
     }
     
     static func callMe() - Promise<Bool {
         return Promise<Bool.init(true)
     }
 }
```
 
 This is the simple use case. The application fails to compile. 
 
I m unable test because it throws an error. 
`Tests in the target “PromisesTests” can’t be run because “PromisesTests” isn’t a member of the active scheme.
`

**Comment by DazChong** [comment] 2018-06-06 14:17
Tested Pod with XCode 10 beta with new blank Cocoa app, 
result in `Swift Compiler Error` > `Include of non-modular header inside framework module 'FBLPromises'...`

And then open project back in XCode 9 will remain to have this error. Clean project, pod remove and add didnt help.

If creating a blank new project with in XCode 9, it works. But broken once opened it with XCode 10 beta.

**Comment by shoumikhin** [comment] 2018-06-06 14:59
@rajesht1989 I just ran the following code successfully in a new 1-view template project set up with Cococapods in Xcode 10 beta:

```ruby
# Podfile
target 'TestPromisesCocoapods' do
  use_frameworks!
  pod 'PromisesSwift', '~> 1.2.2'
end
```

```objc
// TestObject.h
#import <FBLPromises/FBLPromises.h>

@interface TestObject : NSObject
- (void)test;
@end

// TestObject.m
#import "TestPromisesCocoapods-Swift.h"

@implementation TestObject

- (void)test {
  [Test callMeObjc].then(^id(NSNumber *number) {
    NSLog(@"%@",number);
    return nil;
  });
}

@end

// TestPromisesCocoapods-Bridging-Header.h
#import "TestObject.h"
```

```swift
// ViewController.swift
import Promises
import UIKit

class ViewController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()

    TestObject().test()
  }
}

// Test.swift
import Promises

class Test : NSObject {
  
  @objc
  static func callMeObjc() -> Promise<Bool>.ObjCPromise<NSNumber> {
    return callMe().then { value in
      NSNumber(value: value)
    }.asObjCPromise()
  }
  
  static func callMe() -> Promise<Bool> {
    return Promise(true)
  }
}
```

Let me know if it works on your side.

**Comment by rajesht1989** [comment] 2018-06-07 05:45
@shoumikhin We had the same sort of code but It was not working. Now we are able to fix the issue by making return type FBLPromise<NSNumber> like this. 

new working code
```
static func callMeObjc() -> FBLPromise<NSNumber> {
    return callMe().asObjCPromise()
  }
```
Instead of 
```
static func callMeObjc() -> Promise<Bool>.ObjCPromise<NSNumber> {
    return callMe().asObjCPromise()
  }
```

Can you let me know if this is fine and let me know the causes and consequences of this ?

**Comment by shoumikhin** [comment] 2018-06-07 05:49
Do you also have an `@objc` specifier for the function returning `ObjCPromise` and used from Objective-C?
I'd highly appreciate if you packed a simple test project in zip and attached here, so that we could reproduce your error.
Thanks!

**Comment by rajesht1989** [comment] 2018-06-07 07:14
@shoumikhin I have tried giving `@objc`specifier but still helpless. When I try the same in the sample project, It compiled without any issues. 
So, I feel the problem is in the configuration of my project which I could not identify. :(

**Comment by shoumikhin** [comment] 2018-06-07 23:33
Sorry to hear that. Hoped we could help to resolve your issue. Anyhow, feel free to close this issue and follow up with any other related findings in future.

**Comment by Kishimotovn** [comment] 2018-06-08 08:48
@shoumikhin I'm having the same problem with promises and Xcode 10 beta.
Couldn't build FBLPromises:
Include non-modular header inside framework module 'FBLPromises'

The project builds fine with Xcode 9.3 :(

**Comment by Kishimotovn** [comment] 2018-06-08 09:41
This problem is resolved by removing Promises from pod file and reinstall...

**Comment by shoumikhin** [comment] 2018-06-08 16:12
@Kishimotovn just to clarify, do you say the issue has gone when you re-run `pod update`? Were you able to successfully build Promises with Xcode 10 eventually? Would appreciate any reproduction steps that lead to the issue.

**Comment by peterstojanowski** [comment] 2018-06-09 11:46
Hi @shoumikhin, for me it compiles fine on iOS but on macOS I'm getting the same problem as mentioned earlier. You can reproduce it by creating a macOS project and adding the `PromisesSwift` pod.

**Comment by Kishimotovn** [comment] 2018-06-09 13:15
Hi @shoumikhin,

Here is what I did:
- remove the pod from the podfile
- run apod install to remove those pod from the project.
- do a clean build with xcode
- add the pod again to the podfile and install

It seems that this problem only happens when you open an existing project with xcode 10. Projects that are created with xcode 10 won’t have this problem :-?

**Comment by malaratn** [comment] 2018-06-10 06:05
Just turn on Xcode Server. It's good for me.

**Closed** 2018-06-22 19:12 UTC

**Comment by martindufort** [comment] 2018-08-27 18:58
Got that same error under XCode 9.4.1 with version 1.2.3.
`Include of non-modular header inside framework module 'FBLPromises'` 
`..../Sources/Promises/Promise+Await.swift:15:8: Could not build Objective-C module 'FBLPromises'`

**Comment by shoumikhin** [comment] 2018-08-27 19:13
Hi Martin, thank you for reporting that!

Are you using CocoaPods?
Wonder if the following would work for you:

```sh
pod cache clean PromisesObjC
pod cache clean PromisesSwift
cd <your_project_dir>
rm -rf Pods/
rm Podfile.lock
pod update
```

**Comment by martindufort** [comment] 2018-08-27 20:49
Followed instructions... Same issue. 
![screen shot 2018-08-27 at 4 48 51 pm](https://user-images.githubusercontent.com/28934641/44685300-26ffc200-aa19-11e8-8627-0734cb63314a.png)

**Comment by shoumikhin** [comment] 2018-08-27 20:53
Do you mind to make a small test project and check if it reproduces on it, and if so, share the project here with some instructions on how to break it? Many thanks!

**Comment by martindufort** [comment] 2018-08-27 20:53
![screen shot 2018-08-27 at 4 52 59 pm](https://user-images.githubusercontent.com/28934641/44685556-bc02bb00-aa19-11e8-90ad-77ed7b18f397.png)

**Comment by martindufort** [comment] 2018-08-27 20:54
Will do and report here.

**Comment by martindufort** [comment] 2018-08-28 20:53
Weird. I created a new project; installed and compiled the Promises pod without any issues. 
Will investigate my current project structure.

**Comment by martindufort** [comment] 2018-08-29 12:57
OK, I've found the issue I think. 

The umbrella header (PromisesObjc-umbrella.h) included all the FBLPromise+*.h headers. 
And at the end of the file it includes FMLPromises.h which itself re-includes all the FMLPromise+.h headers. 

Commenting out the last include resolve the issue. 

`
#import "FBLPromiseError.h"
// #import "FBLPromises.h"
`

**Comment by martindufort** [comment] 2018-08-29 15:24
Here's my latest finding: 

- Cleaning the project and removing the XCode "DerivedData" folder and then rebuilding works correctly. 

- However If I clean the project but **not do remove** the "DerivedData" folder then it fails with the "non-modular error". 

Not sure where to go for here.

**Comment by shoumikhin** [comment] 2018-08-29 15:58
Thank you for experimenting, Martin!
How do you normally clean the project?

There're basically two standard options via Xcode:

<img width="389" alt="screen shot 2018-08-29 at 8 56 16 am" src="https://user-images.githubusercontent.com/426434/44799726-7ce37f80-ab69-11e8-89c7-d68c8a60d9ab.png">

Wonder if both of them fail to clean `DerivedData` properly?

**Comment by martindufort** [comment] 2018-09-05 14:34
OK, after some tests, even the Clean Build Folder.... does not prevent the compilation failure. 
I have to moved the "DerivedData" folder to the trash to allow my project to build cleanly. 

Weird !!! 

Will have to try with XCode 10 to see if this is a bug that is now resolved...

**Comment by nitishmaropost** [comment] 2018-10-12 07:29
Getting the same issue. I read somewhere that might be because of low memory. But that doesn't help as well.

**Comment by martindufort** [comment] 2018-10-12 09:37
I think it's an issue if you have started your project with an earlier
version of XCode and then upgraded all the way to XCode 10.

The only way I was able to make this work (even in XCode 10) was to
physically delete the DerivedData folder.

**Comment by ItsEcholot** [comment] 2019-05-14 07:56
This randomly happened while adding another library as a pod. Like @martindufort said deleting DerivedData folder fixed it!
