### ISSUE TITLE
Package doesn't have bitcode enabled

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [google/promises#159] opened 2020-08-28 10:29 UTC
When setting Enable BITCODE = Yes in a Flutter iOS project (within Xcode), building the project fails as this package doesn't enabled bitcode.

What makes this worse is that this package is a dependency within the FlutterFire packages so adding any Firebase packages triggers this error when building.

The only solution is to keep bitcode disabled for the Flutter project, which stops us being able to add a WatchOS extension.

**Comment by ykjchen** [comment] 2020-08-28 14:15
Thanks for reporting. A few questions:
1. What dependency management system is used?
2. Is FlutterFire being integrated as a prebuilt framework?
3. Do you have a proposed solution?

**Comment by ykjchen** [comment] 2020-09-27 17:12
I wasn't able to reproduce this using the following steps:
1. create new flutter app,
2. enable bitcode,
3. add watch extension,
4. create Firebase project, add FlutterFire plugins, and run `flutter packages get` (https://firebase.google.com/docs/flutter/setup),
5. run app.

Here's a screenshot showing the state (app running, and Firebase detecting traffic):
<img width="1402" alt="Screen Shot 2020-09-27 at 10 06 50 AM" src="https://user-images.githubusercontent.com/4423897/94371198-a4d7a100-00a9-11eb-9385-c8efe7305484.png">

I have Xcode 12.0 and cocoapods 1.9.3 (I don't know if this is relevant) installed.

Is your project set up differently than this?

**Comment by GenixPL** [comment] 2020-09-29 12:26
Everything is fine when you try to use it on an iOS simulator, problems arise when you try to install an app on a real iPhone.

**Error log:**
`ld: bitcode bundle could not be generated because '/Users/genix/Library/Developer/Xcode/DerivedData/Runner-btxtvcidjpwqqagvqtlbpyewvlyw/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/genix/Library/Developer/Xcode/DerivedData/Runner-btxtvcidjpwqqagvqtlbpyewvlyw/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64`

**Comment by GenixPL** [comment] 2020-10-05 06:56
[https://github.com/flutter/flutter/issues/67285](https://github.com/flutter/flutter/issues/67285) <- repro steps

**Comment by ykjchen** [comment] 2020-10-05 07:22
Thanks for the extra info. I was able to repro.

I don't see bitcode being an option in [pod spec](https://guides.cocoapods.org/syntax/podspec.html). I think the consumer is meant to control enablement. Two options:

1. Manually enable (note that you'll have to manually enable bitcode for all targets, and not just PromisesObjc... I think PromisesObjc just happens to be the first failure here):
<img width="829" alt="Screen Shot 2020-10-05 at 12 19 04 AM" src="https://user-images.githubusercontent.com/4423897/95050458-6f7e1500-06a0-11eb-901a-14429f50119d.png">

2. Add a post_install script to your Podfile that enables bitcode for all targets (the inverse of [this](https://stackoverflow.com/a/32685434)):
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
```

Option 2 is probably more maintainable. This worked for me, so I'll go ahead and close this. Please reopen if it doesn't help. Thanks!

**Closed by ykjchen** 2020-10-05 07:22 UTC
