### ISSUE TITLE
Bug in iOS 16 DevBeta1

### ISSUE THREAD

**Issue by mlch911** [google/promises#185] opened 2022-06-07 09:28 UTC
https://github.com/google/promises/blob/46c1e6b5ac09d8f82c991061c659f67e573d425d/Sources/Promises/Promise%2BAsync.swift#L28
String can convert to NSError in iOS 16.
This most likely is a bug in iOS 16.
Hope Apple could fix this soon.

**Comment by momoraul** [comment] 2022-06-11 16:30
My app also worked strangely on iOS16, so I tried debugging it and the reason was the code above as well.
However, this problem is not only a problem with iOS 16, but potentially also on iOS 15 and lower versions.
Just add this code to your project and the problem will be reproduced regardless of iOS version.

`extension String: Error {}`

It is assumed that the problem occurred in iOS16 because the above code exists in 'SafariServices.framework' of iOS16.

I think this is an issue that needs to be resolved quickly.

**Comment by dmace2** [comment] 2022-06-14 00:21
@ykjchen Can we get someone to look at this? It's a pretty massive issue that breaks a ton of use cases for Promises

**Comment by ykjchen** [comment] 2022-06-14 00:35
Thanks for reporting. It looks like this results in success being handled like an error, in the case where the promise type is String.

Is that the correct read on this?

**Comment by dmace2** [comment] 2022-06-14 00:41
Yes that is correct.

**Comment by momoraul** [comment] 2022-06-14 00:45
> Thanks for reporting. It looks like this results in success being handled like an error, in the case where the promise type is String.
> 
> Is that the correct read on this?

Yes that is correct.
However, currently there is only a problem with the String type in iOS16,
If it extends to Int: Error {}, etc., it may be a problem for other types as well.
For details, refer to the information submitted to the forums.
https://developer.apple.com/forums/thread/708025

**Comment by ykjchen** [comment] 2022-06-14 02:31
Does changing the check from:
```
if let error = value as? NSError { 
```
to something like:
```
if type(of: error) is NSError.Type
```
seem like a possible solution?

(from https://stackoverflow.com/a/44698046)

**Comment by dmace2** [comment] 2022-06-14 02:45
I believe that does work yes.

**Comment by dmace2** [comment] 2022-06-14 03:54
I opened a PR for this here: https://github.com/google/promises/pull/188

**Comment by dmace2** [comment] 2022-06-20 00:55
Is there anything else I need to do in order to get this merged? We are holding off on pushing the next build of our app until this has been resolved

**Comment by ykjchen** [comment] 2022-06-21 02:24
Apologies for the delay, thanks for your patience, just added a review.

**Comment by dmace2** [comment] 2022-06-21 03:19
No worries, just got those changes in so hopefully all is done now

**Comment by dmace2** [comment] 2022-06-23 23:22
Can you make a new release so we can target it in spm? @ykjchen

**Closed** 2022-06-23 23:21 UTC

**Comment by ykjchen** [comment] 2022-06-25 06:54
Sure, it's done now.
